<!DOCTYPE html>
<html>
<head>
	<title>EJERCICIO 3</title>
</head>
<body>
	<h1><center>EJERCICIO 3</center></h1>
	<form action="EJERCICIO3.2.php" method="post">
		<label for="tarifa">Tarifa por día:</label>
		<input type="number" name="tarifa" id="tarifa" required><br><br>
		<label for="dias">Número de días de alquiler:</label>
		<input type="number" name="dias" id="dias" required><br><br>
		<input type="submit" value="Calcular">
	</form>

    
</body>
</html>
